export const circuitsData = [
  { id: "melbourne", name: "Albert Park Circuit", country: "Australia", city: "Melbourne", latitude: -37.8497, longitude: 144.968, length: 5.278, turns: 14, drsZones: 3, type: "street" },
  { id: "shanghai", name: "Shanghai International Circuit", country: "China", city: "Shanghai", latitude: 31.3389, longitude: 121.2197, length: 5.451, turns: 16, drsZones: 2, type: "permanent" },
  { id: "suzuka", name: "Suzuka International Racing Course", country: "Japan", city: "Suzuka", latitude: 34.8431, longitude: 136.5407, length: 5.807, turns: 18, drsZones: 2, type: "permanent" },
  { id: "bahrain", name: "Bahrain International Circuit", country: "Bahrain", city: "Sakhir", latitude: 26.0325, longitude: 50.5106, length: 5.412, turns: 15, drsZones: 3, type: "permanent" },
  { id: "jeddah", name: "Jeddah Corniche Circuit", country: "Saudi Arabia", city: "Jeddah", latitude: 21.6319, longitude: 39.1044, length: 6.174, turns: 27, drsZones: 3, type: "street" },
  { id: "miami", name: "Miami International Autodrome", country: "United States", city: "Miami", latitude: 25.9581, longitude: -80.2389, length: 5.412, turns: 19, drsZones: 3, type: "street" },
  { id: "imola", name: "Autodromo Enzo e Dino Ferrari", country: "Italy", city: "Imola", latitude: 44.3439, longitude: 11.7167, length: 4.909, turns: 19, drsZones: 2, type: "permanent" },
  { id: "monaco", name: "Circuit de Monaco", country: "Monaco", city: "Monte Carlo", latitude: 43.7347, longitude: 7.4206, length: 3.337, turns: 19, drsZones: 1, type: "street" },
  { id: "barcelona", name: "Circuit de Barcelona-Catalunya", country: "Spain", city: "Barcelona", latitude: 41.57, longitude: 2.2611, length: 4.657, turns: 14, drsZones: 2, type: "permanent" },
  { id: "montreal", name: "Circuit Gilles Villeneuve", country: "Canada", city: "Montreal", latitude: 45.5, longitude: -73.5228, length: 4.361, turns: 14, drsZones: 2, type: "street" },
  { id: "spielberg", name: "Red Bull Ring", country: "Austria", city: "Spielberg", latitude: 47.2197, longitude: 14.7647, length: 4.318, turns: 10, drsZones: 3, type: "permanent" },
  { id: "silverstone", name: "Silverstone Circuit", country: "United Kingdom", city: "Silverstone", latitude: 52.0786, longitude: -1.0169, length: 5.891, turns: 18, drsZones: 2, type: "permanent" },
  { id: "spa", name: "Circuit de Spa-Francorchamps", country: "Belgium", city: "Stavelot", latitude: 50.4372, longitude: 5.9714, length: 7.004, turns: 19, drsZones: 2, type: "permanent" },
  { id: "zandvoort", name: "Circuit Zandvoort", country: "Netherlands", city: "Zandvoort", latitude: 52.3888, longitude: 4.5409, length: 4.259, turns: 14, drsZones: 2, type: "permanent" },
  { id: "monza", name: "Autodromo Nazionale Monza", country: "Italy", city: "Monza", latitude: 45.6156, longitude: 9.2811, length: 5.793, turns: 11, drsZones: 2, type: "permanent" },
  { id: "baku", name: "Baku City Circuit", country: "Azerbaijan", city: "Baku", latitude: 40.3725, longitude: 49.8533, length: 6.003, turns: 20, drsZones: 2, type: "street" },
  { id: "singapore", name: "Marina Bay Street Circuit", country: "Singapore", city: "Singapore", latitude: 1.2914, longitude: 103.8639, length: 4.94, turns: 19, drsZones: 3, type: "street" },
  { id: "austin", name: "Circuit of the Americas", country: "United States", city: "Austin", latitude: 30.1328, longitude: -97.6411, length: 5.513, turns: 20, drsZones: 2, type: "permanent" },
  { id: "mexico-city", name: "Autódromo Hermanos Rodríguez", country: "Mexico", city: "Mexico City", latitude: 19.4042, longitude: -99.0907, length: 4.304, turns: 17, drsZones: 3, type: "permanent" },
  { id: "interlagos", name: "Autódromo José Carlos Pace", country: "Brazil", city: "São Paulo", latitude: -23.7036, longitude: -46.6997, length: 4.309, turns: 15, drsZones: 2, type: "permanent" },
  { id: "lusail", name: "Lusail International Circuit", country: "Qatar", city: "Lusail", latitude: 25.49, longitude: 51.4542, length: 5.419, turns: 16, drsZones: 2, type: "permanent" },
  { id: "yas-marina", name: "Yas Marina Circuit", country: "United Arab Emirates", city: "Abu Dhabi", latitude: 24.4672, longitude: 54.6031, length: 5.281, turns: 16, drsZones: 2, type: "permanent" },
  { id: "budapest", name: "Hungaroring", country: "Hungary", city: "Budapest", latitude: 47.5789, longitude: 19.2486, length: 4.381, turns: 14, drsZones: 2, type: "permanent" },
  { id: "madrid", name: "Madrid Street Circuit", country: "Spain", city: "Madrid", latitude: 40.4168, longitude: -3.7038, length: 5.47, turns: 20, drsZones: 3, type: "street" },
  { id: "las-vegas", name: "Las Vegas Street Circuit", country: "United States", city: "Las Vegas", latitude: 36.1147, longitude: -115.1728, length: 6.201, turns: 17, drsZones: 2, type: "street" },
] as const;
