export const factsData = [
  { content: "Monza es conocido como 'El Templo de la Velocidad'. La velocidad media de carrera supera los 250 km/h.", tags: ["monza", "speed", "history"] },
  { content: "El circuito de Mónaco es tan estrecho que un F1 apenas podría adelantar a otro sin DRS. Es la carrera más lenta del calendario.", tags: ["monaco", "circuits"] },
  { content: "Lewis Hamilton tiene más poles que cualquier otro piloto en la historia con 104.", tags: ["hamilton", "ferrari", "records"] },
  { content: "El GP de Mónaco se corre desde 1929, siendo una de las carreras más antiguas del automovilismo mundial.", tags: ["monaco", "history"] },
  { content: "Michael Schumacher ganó 5 campeonatos consecutivos con Ferrari entre 2000 y 2004.", tags: ["ferrari", "records", "history"] },
  { content: "El circuito de Spa-Francorchamps tiene 7 km de largo, el más extenso del calendario actual.", tags: ["spa", "circuits"] },
  { content: "Max Verstappen se convirtió en el piloto más joven en ganar una carrera de F1 a los 18 años y 228 días en Barcelona 2016.", tags: ["verstappen", "red-bull", "records"] },
  { content: "El Halo, introducido en 2018, está hecho de titanio y puede soportar el peso de un autobús de dos pisos.", tags: ["safety", "technical"] },
  { content: "Un motor de F1 gira a más de 15.000 RPM y produce más de 1000 caballos de fuerza combinados.", tags: ["technical", "power-unit"] },
  { content: "Los neumáticos de F1 alcanzan temperaturas de hasta 120°C durante la carrera.", tags: ["tires", "technical"] },
  { content: "Ayrton Senna ganó 6 veces el GP de Mónaco, un récord que todavía se mantiene.", tags: ["monaco", "history", "records"] },
  { content: "El primer GP de F1 se corrió en Silverstone el 13 de mayo de 1950. Giuseppe Farina ganó con Alfa Romeo.", tags: ["silverstone", "history"] },
  { content: "Ferrari es el equipo más exitoso de la historia con 16 campeonatos de constructores.", tags: ["ferrari", "records"] },
  { content: "Un pit stop moderno dura menos de 2 segundos. El récord es de 1.80 segundos por Red Bull en 2019.", tags: ["pit-stops", "records", "red-bull"] },
  { content: "Los frenos de carbono de un F1 alcanzan 1000°C y pueden frenar el auto de 300 km/h a 0 en menos de 4 segundos.", tags: ["technical", "brakes"] },
  { content: "El downforce generado por un F1 a velocidad máxima es suficiente para que el auto conduzca boca abajo en un túnel.", tags: ["aero", "technical"] },
  { content: "Juan Manuel Fangio ganó 5 campeonatos mundiales en los años 50, un récord que duró 46 años hasta que Schumacher lo superó.", tags: ["history", "records"] },
  { content: "La curva Eau Rouge de Spa-Francorchamps se toma a más de 300 km/h y es considerada una de las más icónicas del automovilismo.", tags: ["spa", "circuits"] },
  { content: "Suzuka es el único circuito de F1 con un trazado en forma de ocho, donde la pista se cruza sobre sí misma.", tags: ["suzuka", "circuits"] },
  { content: "Un piloto de F1 pierde entre 2 y 4 kg de peso corporal durante una carrera por la deshidratación.", tags: ["drivers", "physical"] },
  { content: "El reglamento 2026 introduce la aerodinámica activa: los alerones cambian de forma según la velocidad del auto.", tags: ["2026", "technical", "aero"] },
  { content: "Williams ganó 9 campeonatos de constructores entre 1980 y 1997, siendo una de las épocas más dominantes de un equipo.", tags: ["williams", "history", "records"] },
  { content: "El circuito callejero de Jeddah es el más rápido del mundo con velocidades promedio de más de 250 km/h.", tags: ["jeddah", "circuits", "speed"] },
  { content: "Kimi Räikkönen disputó 353 Grandes Premios, el récord absoluto de carreras en F1.", tags: ["records", "history"] },
  { content: "En el GP de Canadá 2011, Jenson Button remontó desde el último lugar hasta la victoria bajo la lluvia.", tags: ["montreal", "history", "races"] },
  { content: "El volante de un F1 tiene más de 20 botones y controles, y cuesta aproximadamente $50.000 USD.", tags: ["technical", "steering"] },
  { content: "Cadillac se suma como el 11vo equipo en 2026, la primera vez desde Haas en 2016 que se agrega un equipo nuevo.", tags: ["cadillac", "2026"] },
  { content: "Audi reemplaza a Sauber en 2026, convirtiéndose en el primer fabricante alemán nuevo en F1 desde Mercedes en 2010.", tags: ["audi", "2026"] },
  { content: "El GP de Singapur fue la primera carrera nocturna de F1, celebrada en 2008 bajo luces artificiales.", tags: ["singapore", "history", "circuits"] },
  { content: "Un F1 puede generar hasta 6G de fuerza lateral en curvas de alta velocidad, comparable a un avión de combate.", tags: ["technical", "physical"] },
] as const;
