export const glossaryData = [
  { term: "DRS", definition: "Drag Reduction System. Sistema que abre el alerón trasero en rectas designadas para reducir la resistencia aerodinámica y facilitar adelantamientos.", category: "aero" },
  { term: "MGU-K", definition: "Motor Generator Unit - Kinetic. Convierte la energía cinética del frenado en energía eléctrica, y viceversa para propulsar el auto.", category: "power-unit" },
  { term: "MGU-H", definition: "Motor Generator Unit - Heat. Recupera energía del calor de los gases de escape del turbo. Eliminado en el reglamento 2026.", category: "power-unit" },
  { term: "Downforce", definition: "Fuerza aerodinámica que empuja el auto hacia el suelo, aumentando el agarre mecánico en curvas a costa de mayor resistencia en rectas.", category: "aero" },
  { term: "Undercut", definition: "Estrategia de pit stop donde un piloto entra antes que su rival para aprovechar neumáticos frescos y ganar posición.", category: "strategy" },
  { term: "Overcut", definition: "Estrategia opuesta al undercut: quedarse en pista más tiempo con neumáticos viejos para ganar posición cuando el rival hace su parada.", category: "strategy" },
  { term: "Porpoising", definition: "Rebote vertical del auto causado por la pérdida y recuperación intermitente del efecto suelo a alta velocidad.", category: "aero" },
  { term: "Ground Effect", definition: "Efecto suelo. Generación de downforce mediante el flujo de aire acelerado bajo el piso del auto, creando una zona de baja presión.", category: "aero" },
  { term: "Halo", definition: "Estructura de titanio en forma de aureola sobre el cockpit que protege la cabeza del piloto de impactos y escombros.", category: "safety" },
  { term: "Safety Car", definition: "Auto de seguridad que sale a pista para neutralizar la carrera cuando hay un incidente que requiere intervención en condiciones peligrosas.", category: "race" },
  { term: "VSC", definition: "Virtual Safety Car. Sistema que reduce la velocidad de todos los autos mediante un delta time sin necesidad de un safety car físico.", category: "race" },
  { term: "ERS", definition: "Energy Recovery System. Sistema que recupera y almacena energía cinética y térmica para reutilizarla como potencia adicional.", category: "power-unit" },
  { term: "Slipstream", definition: "Rebufo. Zona de aire con menor resistencia detrás de otro auto, que permite alcanzar mayor velocidad en rectas.", category: "aero" },
  { term: "Dirty Air", definition: "Aire turbulento dejado por un auto que reduce el downforce del auto que lo sigue, dificultando el seguimiento en curvas.", category: "aero" },
  { term: "Clean Air", definition: "Aire sin perturbaciones aerodinámicas, donde el auto produce su máximo downforce. Es la condición ideal de carrera.", category: "aero" },
  { term: "Compound", definition: "Tipo de goma del neumático. Pirelli ofrece 5 compuestos: Soft (blando, rápido pero corta vida), Medium, Hard, Intermediate y Wet.", category: "tires" },
  { term: "Degradation", definition: "Pérdida progresiva de rendimiento del neumático con el uso. Varía según compuesto, temperatura y estilo de conducción.", category: "tires" },
  { term: "Graining", definition: "Pequeñas bolitas de goma que se forman en la superficie del neumático cuando no alcanza su temperatura óptima de trabajo.", category: "tires" },
  { term: "Blistering", definition: "Ampollas que se forman en el neumático cuando el interior se sobrecalienta, causando separación entre capas de goma.", category: "tires" },
  { term: "Drag", definition: "Resistencia aerodinámica. Fuerza que se opone al avance del auto. Se busca minimizar en rectas y aceptar más en curvas.", category: "aero" },
] as const;
