export const teamsData = [
  {
    id: "mclaren",
    name: "McLaren",
    fullName: "McLaren Racing",
    colorPrimary: "#FF8000",
    base: "Woking, United Kingdom",
    teamPrincipal: "Andrea Stella",
    engine: "Mercedes",
    firstSeason: 1966,
    championships: 9,
    wins: 188,
    podiums: 508,
  },
  {
    id: "mercedes",
    name: "Mercedes",
    fullName: "Mercedes-AMG Petronas F1 Team",
    colorPrimary: "#27F4D2",
    base: "Brackley, United Kingdom",
    teamPrincipal: "Toto Wolff",
    engine: "Mercedes",
    firstSeason: 2010,
    championships: 8,
    wins: 125,
    podiums: 290,
  },
  {
    id: "red-bull",
    name: "Red Bull",
    fullName: "Oracle Red Bull Racing",
    colorPrimary: "#3671C6",
    base: "Milton Keynes, United Kingdom",
    teamPrincipal: "Christian Horner",
    engine: "Ford-RBPT",
    firstSeason: 2005,
    championships: 7,
    wins: 121,
    podiums: 260,
  },
  {
    id: "ferrari",
    name: "Ferrari",
    fullName: "Scuderia Ferrari HP",
    colorPrimary: "#E8002D",
    base: "Maranello, Italy",
    teamPrincipal: "Frédéric Vasseur",
    engine: "Ferrari",
    firstSeason: 1950,
    championships: 16,
    wins: 247,
    podiums: 820,
  },
  {
    id: "williams",
    name: "Williams",
    fullName: "Williams Racing",
    colorPrimary: "#64C4FF",
    base: "Grove, United Kingdom",
    teamPrincipal: "James Vowles",
    engine: "Mercedes",
    firstSeason: 1978,
    championships: 9,
    wins: 114,
    podiums: 313,
  },
  {
    id: "racing-bulls",
    name: "Racing Bulls",
    fullName: "Visa Cash App Racing Bulls",
    colorPrimary: "#6692FF",
    base: "Faenza, Italy",
    teamPrincipal: "Laurent Mekies",
    engine: "Ford-RBPT",
    firstSeason: 2006,
    championships: 0,
    wins: 2,
    podiums: 12,
  },
  {
    id: "aston-martin",
    name: "Aston Martin",
    fullName: "Aston Martin Aramco F1 Team",
    colorPrimary: "#229971",
    base: "Silverstone, United Kingdom",
    teamPrincipal: "Adrian Newey",
    engine: "Honda",
    firstSeason: 2021,
    championships: 0,
    wins: 1,
    podiums: 14,
  },
  {
    id: "haas",
    name: "Haas",
    fullName: "MoneyGram Haas TGR F1 Team",
    colorPrimary: "#B6BABD",
    base: "Kannapolis, United States",
    teamPrincipal: "Ayao Komatsu",
    engine: "Ferrari",
    firstSeason: 2016,
    championships: 0,
    wins: 0,
    podiums: 1,
  },
  {
    id: "audi",
    name: "Audi",
    fullName: "Audi F1 Team",
    colorPrimary: "#C0C0C0",
    base: "Hinwil, Switzerland",
    teamPrincipal: "Mattia Binotto",
    engine: "Audi",
    firstSeason: 2026,
    championships: 0,
    wins: 0,
    podiums: 0,
  },
  {
    id: "alpine",
    name: "Alpine",
    fullName: "BWT Alpine F1 Team",
    colorPrimary: "#FF87BC",
    base: "Enstone, United Kingdom",
    teamPrincipal: "Oliver Oakes",
    engine: "Mercedes",
    firstSeason: 2021,
    championships: 0,
    wins: 1,
    podiums: 5,
  },
  {
    id: "cadillac",
    name: "Cadillac",
    fullName: "Cadillac F1 Team",
    colorPrimary: "#1A1A1A",
    base: "United States",
    teamPrincipal: "Graeme Lowdon",
    engine: "Ferrari",
    firstSeason: 2026,
    championships: 0,
    wins: 0,
    podiums: 0,
  },
] as const;
